# Site settings
title: "Clubs and Crawfish"
email: "clubsandcrawfish@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "//clubsandcrawfish.com" # the base hostname & protocol for your site

instagram_username: "walnutfarm_montessori"
facebook_username: "WalnutFarm"

repository: npadley/clubsandcrawfish

collections:
  - sponsors

gems:
  - jekyll-email-protect