backend:
  name: github
  repo: npadley/clubsandcrawfish
  branch: master

media_folder: "img/uploads"

collections:
  - name: "page"
    label: "Page"
    folder: "pages"
    create: true
    fields:
        - {label: "Title", name: "title", widget: "string", tagname: "h1"}
        - {label: "Permalink", name: "permalink", widget: "string"}
        - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
        - {label: "Body", name: "body", widget: "markdown"}
  - name: "sponsors"
    label: "Sponsors"
    folder: "_sponsors"
    fields:
        - {label: "Type", name: "type", widget: "string", tagname: "h1"}
        - {label: "Amount", name: "amount", widget: "string"}
        - {label: "Spaces", name: "spaces", widget: "number"}
        - {label: "Image", name: "image", widget: "image"}
        - {label: "Body", name: "body", widget: "markdown"}